services:
  api-server:
    container_name: api-server
    build: &api-server
      context: .
      dockerfile: docker/api-server/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_started

  
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    volumes:
      - postgres_data:/var/lib/postgresql/data 


volumes:
  postgres_data: